postgresql:
  url: postgresql+asyncpg://media_user:qwerty@127.0.0.1:5432/media_db

ftp:
  host: 127.0.0.1
  user: username
  passwd: mypass
  imagepath: /images
  tmpimagepath: /tmpimages

redis:
  url: redis://localhost:6379/0
