postgresql:
  # substring "postgres" in URL is a link to docker container database (see docker-compose.yml)
  url: postgresql+asyncpg://media_user:qwerty@postgres:5432/media_db

ftp:
  host: ftp-server # link to docker container ftp-server (see docker-compose.yml)
  user: username
  passwd: mypass
  imagepath: /images
  tmpimagepath: /tmpimages

redis:
  # substring "red" in URL is a link to docker container redis-server (see docker-compose.yml)
  url: redis://red:6379/0
